import type { Metadata } from 'next';
import { Zen_Antique } from 'next/font/google';
import { NextuiThemeProviders } from '@/app/components/providers/NextuiThemeProviders';
import { Suspense } from 'react';
import Loading from './loading';
import './globals.css';

const zen = Zen_Antique({
  weight: '400',
  display: 'swap',
  preload: true,
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'fullstack-nextjs-with-nextui-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning={true}>
      <body className={zen.className}>
        <NextuiThemeProviders>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </NextuiThemeProviders>
      </body>
    </html>
  );
}
